version: '3.7'
services:
  dev-nodejs:
    container_name: prostoregress-dev-nodejs
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/var/www/app
    ports:
      - "${DOCKER_PORT_DEV}:3030"