version: '3.7'
services:
  prod-client:
    container_name: prostoregress-prod
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    volumes:
      - ./docker/prod/nginx/default.conf:/etc/nginx/nginx.conf:ro
    networks:
      - prod
  prod-proxer:
    image: nginx:latest
    container_name: prostoregress-prod-nginx
    ports:
      - "${DOCKER_PORT_PROD_HTTP}:80"
      - "${DOCKER_PORT_PROD_HTTPS}:443"
    volumes:
      - ./docker/prod/nginx/conf.d/ssl_certificate.conf:/etc/nginx/conf.d/default.conf
      - ./docker/letsencrypt/certbot/conf:/etc/letsencrypt
      - ./docker/letsencrypt/certbot/www:/var/www/certbot
    depends_on:
      - prod-client
    # Перезапустит контейнер в непредвиденных ситуациях
    restart: unless-stopped
    # Перезапустит nginx контейнер каждые 6 часов и подгрузит новые сертификаты, если есть
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    networks:
      - prod
  prod-proxer-certbot:
    container_name: prostoregress-prod-certbot
    image: certbot/certbot
    volumes:
      - ./docker/letsencrypt/certbot/conf:/etc/letsencrypt
      - ./docker/letsencrypt/certbot/www:/var/www/certbot
    # Перезапустит контейнер в непредвиденных ситуациях
    restart: unless-stopped
    # Проверяет каждые 12 часов, нужны ли новые сертификаты
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  prod: