version: '3.7'
services:
  develop:
    container_name: prostoregress-develop
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/var/www/app
    ports:
      - "${DOCKER_PORT_DEV}:3030"
    networks:
      - develop
networks:
  develop:
    driver: bridge