/** 1 Node - Modules, Components, Hooks, Icons */
import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";

/** 2 App - Components, Hooks */
/** 3 Entities, Stores, Packages, Enums ... */
import "@/app/globals.scss";
import {AppLayoutHeader} from "@/components/app/layout/header/AppLayoutHeader";
import {AppLayoutFooter} from "@/components/app/layout/footer/AppLayoutFooter";
import {AppThemeProvider} from "@/components/app/theme/provider/AppThemeProvider";
import {AppToaster} from "@/components/app/toaster/AppToaster";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
      <html lang="en">
      <head>
          <meta charSet="UTF-8" />
          <link rel="icon" type="image/svg+xml" href="/favicon.ico" />
          <link rel="apple-touch-icon"  sizes="180x180" href="/favicons/apple-touch-icon.png"/>
          <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png"/>
          <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png"/>
          <link rel="icon" type="image/png" sizes="512x512" href="/favicons/android-chrome-512x512.png"/>
          <link rel="icon" type="image/png" sizes="192x192" href="/favicons/android-chrome-192x192.png"/>
          <link rel="shortcut icon" type="image/x-icon"  href="/favicon.ico"/>
          <link rel="icon" type="image/x-icon"  href="/favicon.ico"/>
          <meta name="msapplication-TileColor" content="#ffffff"/>
          <meta name="msapplication-TileImage" content="/favicon-144x144.png"/>
          <meta name="msapplication-config" content="/browserconfig.xml"/>
          <link rel="manifest" href="/favicons/site.webmanifest"/>
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>Оговорки подсознания|Оговорки подсознания - ваш путь к совершенству</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div id="scroll-to-top" />
        <AppThemeProvider>
            <main className="flex flex-col justify-between max-w-7xl px-4 min-h-screen mx-auto">
                <AppLayoutHeader className="py-4 mx-auto max-w-7xl sticky top-0 z-10 bg-card w-full" />
                {children}
                <AppLayoutFooter className="py-4 mx-auto max-w-7xl" />
            </main>
            <AppToaster />
        </AppThemeProvider>
      </body>
    </html>
  );
}
